# NumPy Arrays:
* vectors - 1 dimensional
* matrices - 2 dimensional

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# creating an array from range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 1 dimensional arrays will have 1 set of brackets []
* 2 dimensional arrays will have 2 sets of brackets [[]]

In [5]:
# creating an identity matrix
    # where number of rows is the same as number of columns - are square
    # istrizaine of 1s
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
# creating arrays of random numbers - from a uniform distribution (ie between 0 and 1)
np.random.rand(5)

array([0.69108664, 0.86182048, 0.51618722, 0.06149096, 0.22687762])

In [8]:
# creating 2-dimensional arrays of random numbers (pass in dimensions of matrix) - from a uniform distribution
np.random.rand(5, 5) 

array([[0.43529446, 0.93807004, 0.10569189, 0.54607244, 0.49760588],
       [0.29907175, 0.6872237 , 0.43627065, 0.87879164, 0.00767266],
       [0.02214145, 0.05042751, 0.46512673, 0.80610189, 0.42227098],
       [0.79143351, 0.54722929, 0.42514509, 0.69712398, 0.16326895],
       [0.78634001, 0.56077526, 0.84895197, 0.55746441, 0.98607916]])

In [12]:
# random - standard normal distribution (pass in how many numbers to generate)
np.random.randn(2)

array([-1.4272522 , -0.33986652])

In [13]:
# generates a random interger from specified min-max range (exclusive on the high-end)
np.random.randint(1, 100)

58

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
rand_array = np.random.randint(0, 50, 10)
rand_array

array([ 1, 37, 39,  4, 37, 17, 16, 11, 36, 32])

In [17]:
# reshaping array into matrix - provide number of rows & columns
arr.reshape(5, 5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
rand_array.max()

39

In [20]:
rand_array.min()

1

In [21]:
# to find the index location of min/max value - +1 to know exact position
rand_array.argmax()

2

# NumPy Indexing and Selection

1 dimensional arrays

In [30]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[8] # getting value at index 8

8

In [25]:
arr[1:5] # exclusive of the high-end 

array([1, 2, 3, 4])

In [27]:
arr[:6] # up to index 6 

array([0, 1, 2, 3, 4, 5])

In [28]:
arr[5:] # grabs everything starting with index 6 

array([ 5,  6,  7,  8,  9, 10])

In [29]:
# reassigning different values to the specified slice
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

if you assign a slice of array to a separate variable and make modifications to that slice - you will end up changing values of the actual array
- must create a copy of array, before manipulating its data

In [33]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2 dimensional arrays

In [35]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[0, 0] # element in the 1st row & 1st column

5

In [37]:
arr_2d[0] # all elements of 1st row

array([ 5, 10, 15])

In [40]:
arr_2d[2, 1]

40

In [42]:
arr_2d[:2, 1:] # up to row index 2, from column index 1 onwards

array([[10, 15],
       [25, 30]])

In [44]:
# conditional selection
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
bool_arr = arr > 5
# using the boolean array to select elements of original array where condition is True
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [48]:
# also could do
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [50]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# NumPy Operations

In [52]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# adding arrays
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
# adding scalar (ie a single number)
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [55]:
np.sqrt(arr) # square root of everything in array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
np.exp(arr) # calculating the exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [57]:
np.max(arr)

10

most common mathematical operations are built into numpy - refer to the ufunc page in course materials